<?php  exit();
/*
Page: /cw/makehtml_homepage.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:20:07
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_homepage.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:20:09
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:20:12
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:20:13
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_all.php?action=make&step=2&uptype=time&mkvalue=1503936000
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:20:17
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=3&isremote=0&serviterm=
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:30:32
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list_action.php?typeid=0&maxpagesize=50&upnext=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:30:38
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list_action.php?typeid=0&maxpagesize=50&upnext=1
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:30:40
*/
?>
<?php  exit();
/*
Page: /cw/makehtml_list_action.php?gotype=&uppage=0&maxpagesize=50&typeid=0&pageno=2&isremote=0&serviterm=
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-08-29 10:30:42
*/
?>
