<?php
$z[0]=Array("arcurl","",131,146);
$z[1]=Array("arcurl","",182,197);
$z[2]=Array("fulltitle","",223,241);
$z[3]=Array("litpic","",263,278);
$z[4]=Array("fulltitle","",285,303);
$z[5]=Array("typelink","",417,434);
$z[6]=Array("arcurl","",500,515);
$z[7]=Array("fulltitle","",541,559);
$z[8]=Array("title","",561,575);
$z[9]=Array("description","",609,629);
$z[10]=Array("pubdate","",669,720);
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";

?>