<li> </li>
		    </ul>
		  </div>
		<ul><li><div class="viewimg"><div class="hotimgzz"></div>
		  <div align="center"><a href="[field:arcurl/]" class="zzsz">
		    </a><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">
		      <img src="[field:litpic/]" alt="[field:fulltitle/]" width="250" height="165"/>
		      </a>
		    </div>
		  <div class="standpoint">
		    <div align="center">[field:typelink/]</div>
		  </div>
					</div>
					<h3 align="center"><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">[field:title/]</a></h3>
					<p align="center">[field:description/]...</p>
					<div align="center"><span>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</span>
					      </div>
		</li>
                <div align="center">