<li>
			
					<div class="viewimg"><div class="hotimgzz"></div><a href="[field:arcurl/]" class="zzsz">
						</a><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">
							<img src="[field:litpic/]" alt="[field:fulltitle/]" width="250" height="165"/>
						</a>
						<div class="standpoint">[field:typelink/]</div>
					</div>
					<h3><a href="[field:arcurl/]"  target="_blank" title="[field:fulltitle/]">[field:title/]</a></h3>
					<p>[field:description/]...</p>
					<span>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</span>
				</li>