<?php
$z[0]=Array("arcurl","",74,89);
$z[1]=Array("arcurl","",125,140);
$z[2]=Array("fulltitle","",166,184);
$z[3]=Array("litpic","",205,220);
$z[4]=Array("fulltitle","",227,245);
$z[5]=Array("typelink","",317,334);
$z[6]=Array("arcurl","",373,388);
$z[7]=Array("fulltitle","",414,432);
$z[8]=Array("title","",434,448);
$z[9]=Array("description","",467,487);
$z[10]=Array("pubdate","",507,558);
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";

?>