<?php
$z[0]=Array("global","",23,48);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","",503,526);
$z[1][4]['name']="id";
$z[2]=Array("global","",958,990);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1149,1181);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1338,1370);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("php","\r\n								for (\$i = 1; \$i < 12; \$i++)\r\n								{\r\n                                    \$isecheck = (\$i == 1) ? 'checked=\"1\" ' : '';\r\n								    echo '<li><input type=\"radio\" name=\"face\" value=\"'.\$i.'\" '.\$isecheck.'/><img src=\"'.\$cfg_templets_skin.'/images/mood/ico-mood-'.\$i.'.gif\" /></li>';\r\n								}\r\n								",1592,1925);
$z[6]=Array("global","",2492,2518);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("php","\r\n								if(\$cfg_mb_open=='Y') {\r\n              		echo '<script language=\"javascript\" type=\"text/javascript\">CheckLogin();</script>';\r\n              	}\r\n							",2819,3001);
$z[8]=Array("field","",3390,3417);
$z[8][4]['name']="phpurl";
$z[9]=Array("field","",3435,3451);
$z[9][4]['name']="id";
$z[10]=Array("global","",4002,4027);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("global","",4167,4193);
$z[11][4]['name']="cfg_phpurl";
$z[12]=Array("field","",4231,4247);
$z[12][4]['name']="id";
$z[13]=Array("global","",4587,4612);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("global","",5500,5528);
$z[14][4]['name']="cfg_soft_lang";
$z[15]=Array("field","",5594,5610);
$z[15][4]['name']="id";
$z[16]=Array("global","",5953,5978);
$z[16][4]['name']="cfg_phpurl";
$z[17]=Array("global","",6117,6142);
$z[17][4]['name']="cfg_cmsurl";

?>