<?php
$z[0]=Array("global","",61,89);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",102,121);
$z[1][4]['name']="title";
$z[2]=Array("global","",122,148);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",568,587);
$z[3][4]['name']="title";
$z[4]=Array("field","",679,735);
$z[4][4]['name']="pubdate";
$z[4][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[5]=Array("field","",984,1006);
$z[5][4]['name']="ckplayer";
$z[6]=Array("field","",1413,1435);
$z[6][4]['name']="ckplayer";
$z[7]=Array("field","",1774,1792);
$z[7][4]['name']="body";
$z[8]=Array("include","",1890,1929);
$z[8][4]['filename']="footer_m.htm";

?>