<?php
$z[0]=Array("item","",2,87);
$z[0][4]['name']="播放器配置方案";
$z[0][4]['link']="ckplayercommon_main.php";
$z[0][4]['rank']="";
$z[0][4]['target']="main";
$z[1]=Array("item","",89,171);
$z[1][4]['name']="播放器风格商城";
$z[1][4]['link']="ckplayer_dlstyle.php";
$z[1][4]['rank']="";
$z[1][4]['target']="main";
$z[2]=Array("item","",173,255);
$z[2][4]['name']="关于ckplayer插件";
$z[2][4]['link']="ckplayer_about.php";
$z[2][4]['rank']="";
$z[2][4]['target']="main";

?>