<field:body itemname="ÎÄÕÂÄÚÈÝ" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:cwckplayer itemname="ckplayer" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:cwckplayer>
<field:pdfurl itemname="pdfurl" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pdfurl>


