<?php
$z[0]=Array("global","",61,88);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",99,124);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("field","",135,169);
$z[2][4]['name']="video_address";
$z[3]=Array("field","",184,218);
$z[3][4]['name']="html5_address";
$z[4]=Array("field","",230,249);
$z[4][4]['name']="title";
$z[5]=Array("field","",262,282);
$z[5][4]['name']="litpic";
$z[6]=Array("field","",296,324);
$z[6][4]['name']="keytime";
$z[7]=Array("field","",338,366);
$z[7][4]['name']="keyword";
$z[8]=Array("field","global \$cfg_cmsurl;if(@me == ''){@me = '';}else{\r\n@me = '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/offlights.js\"></script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/ckplayer.js\"></script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\">document.write(\"<div style=\\\"width:\"+ckdata[\"dwidth\"]+\"px;height:\"+ckdata[\"dheight\"]+\"px;margin:5px auto;clear:both;\\\"><div id=\\\"a1\\\" style=\\\"position:relative;z-index:100;width:100%;height:100%\\\"></div></div>\")</script>'.chr(13);\r\n@me .= '<script type=\"text/javascript\" src=\"'.\$cfg_cmsurl.'/ckplayer/player_pc.js\"></script>';}\r\n",434,1124);
$z[8][4]['name']="video_address";
$z[8][4]['runphp']="yes";

?>