<?php
$z[0]=Array("global","",84,110);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n				<li><a href='list.php?tid=[field:id/]' [field:rel/]><span>[field:typename/]</span></a>\r\n				</li>",589,853);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[2]=Array("global","",968,993);
$z[2][4]['name']="cfg_cmsurl";

?>