<?php
$z[0]=Array("global","",65,93);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",241,271);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",310,337);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",1278,1304);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\r\n						<li> <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a>\r\n						</li>",1712,1843);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[6]=Array("field","",1892,1913);
$z[6][4]['name']="content";
$z[7]=Array("include","",1913,1952);
$z[7][4]['filename']="footer_m.htm";

?>